// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3I5h18VhegPoRsDjzGQyKDyje00uc1g',
    appId: '1:502081899828:web:57aa15a927d8657858e961',
    messagingSenderId: '502081899828',
    projectId: 'flutter-development-cour-9e0f3',
    authDomain: 'flutter-development-cour-9e0f3.firebaseapp.com',
    storageBucket: 'flutter-development-cour-9e0f3.firebasestorage.app',
    measurementId: 'G-MQ234ZY662',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGszeLZkYyQbUvcQFTtymawGI9pemoX8c',
    appId: '1:502081899828:android:1a24a1904cbd484f58e961',
    messagingSenderId: '502081899828',
    projectId: 'flutter-development-cour-9e0f3',
    storageBucket: 'flutter-development-cour-9e0f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEtoWrcIP8-3p3oUqVhD3ElHZWNUS2nHI',
    appId: '1:502081899828:ios:7b37b3d7eb1e5ace58e961',
    messagingSenderId: '502081899828',
    projectId: 'flutter-development-cour-9e0f3',
    storageBucket: 'flutter-development-cour-9e0f3.firebasestorage.app',
    iosBundleId: 'com.example.completeFlutterDartDevelopmentCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEtoWrcIP8-3p3oUqVhD3ElHZWNUS2nHI',
    appId: '1:502081899828:ios:7b37b3d7eb1e5ace58e961',
    messagingSenderId: '502081899828',
    projectId: 'flutter-development-cour-9e0f3',
    storageBucket: 'flutter-development-cour-9e0f3.firebasestorage.app',
    iosBundleId: 'com.example.completeFlutterDartDevelopmentCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb3I5h18VhegPoRsDjzGQyKDyje00uc1g',
    appId: '1:502081899828:web:fa3df28b7e8beb7758e961',
    messagingSenderId: '502081899828',
    projectId: 'flutter-development-cour-9e0f3',
    authDomain: 'flutter-development-cour-9e0f3.firebaseapp.com',
    storageBucket: 'flutter-development-cour-9e0f3.firebasestorage.app',
    measurementId: 'G-L1L8P8BNQD',
  );
}
